
default : usage

usage :
	@echo "Usage:"
	@echo "  make all"
	@echo "  make clean"
	@echo "  make -f Makefile.projection"
	@echo "  make -f Makefile.projection all"
	@echo "  make -f Makefile.projection clean"

all : test_projection

test_projection :
	make -f Makefile.projection all

clean :
	make -f Makefile.projection clean

