OPENSCAD=/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD

default : usage

usage :
	@echo "Usage:"
	@echo "  make all"
	@echo "  make test_hollow_cube_projection_true.dxf"
	@echo "  make test_hollow_cube_projection_false.dxf"
	@echo "  make test_complex_cube_projection_true.dxf"
	@echo "  make test_complex_cube_projection_false.dxf"
	@echo "  make test_hollow_cube_import_projection_true.dxf"
	@echo "  make test_hollow_cube_import_projection_false.dxf"
	@echo "  make test_complex_cube_import_projection_true.dxf"
	@echo "  make test_complex_cube_import_projection_false.dxf"
	@echo "  make intersection_projection_true_diff.dxf"

all : test_hollow_cube_projection_true.dxf test_hollow_cube_projection_false.dxf test_complex_cube_projection_true.dxf test_complex_cube_projection_false.dxf test_hollow_cube_import_projection_true.dxf test_hollow_cube_import_projection_false.dxf test_complex_cube_import_projection_true.dxf test_complex_cube_import_projection_false.dxf intersection_projection_true_diff.dxf 

test_hollow_cube_projection.scad :
	echo "projection_cut=true;" > test_hollow_cube_projection.scad
	echo "projection(cut=projection_cut) difference() {" >> test_hollow_cube_projection.scad
	echo "  cube(size=10.0,center=true);" >> test_hollow_cube_projection.scad
	echo "  cube(size=8.0,center=true);" >> test_hollow_cube_projection.scad
	echo "}" >> test_hollow_cube_projection.scad

test_hollow_cube_projection_true.dxf : test_hollow_cube_projection.scad
	$(OPENSCAD) -D projection_cut=true -x test_hollow_cube_projection_true.dxf test_hollow_cube_projection.scad

test_hollow_cube_projection_false.dxf : test_hollow_cube_projection.scad
	$(OPENSCAD) -D projection_cut=false -x test_hollow_cube_projection_false.dxf test_hollow_cube_projection.scad

test_complex_cube_projection.scad :
	echo "projection_cut=true;" > test_complex_cube_projection.scad
	echo "projection(cut=projection_cut) difference() {" >> test_complex_cube_projection.scad
	echo " rotate([30,30,30]) difference() {" >> test_complex_cube_projection.scad
	echo "  cube(size=10.0,center=true);" >> test_complex_cube_projection.scad
	echo "  cube(size=8.0,center=true);" >> test_complex_cube_projection.scad
	echo " }" >> test_complex_cube_projection.scad
	echo " cube(size=10.0,center=false);" >> test_complex_cube_projection.scad
	echo "}" >> test_complex_cube_projection.scad

test_complex_cube_projection_true.dxf : test_complex_cube_projection.scad
	$(OPENSCAD) -D projection_cut=true -x test_complex_cube_projection_true.dxf test_complex_cube_projection.scad

test_complex_cube_projection_false.dxf : test_complex_cube_projection.scad
	$(OPENSCAD) -D projection_cut=false -x test_complex_cube_projection_false.dxf test_complex_cube_projection.scad

test_hollow_cube_import.scad :
	echo "difference() {" > test_hollow_cube_import.scad
	echo "  cube(size=10.0,center=true);" >> test_hollow_cube_import.scad
	echo "  cube(size=8.0,center=true);" >> test_hollow_cube_import.scad
	echo "}" >> test_hollow_cube_import.scad

test_complex_cube_import.scad :
	echo "difference() {" > test_complex_cube_import.scad
	echo " rotate([30,30,30]) difference() {" >> test_complex_cube_import.scad
	echo "  cube(size=10.0,center=true);" >> test_complex_cube_import.scad
	echo "  cube(size=8.0,center=true);" >> test_complex_cube_import.scad
	echo " }" >> test_complex_cube_import.scad
	echo " cube(size=10.0,center=false);" >> test_complex_cube_import.scad
	echo "}" >> test_complex_cube_import.scad

test_hollow_cube_import.stl : test_hollow_cube_import.scad
	$(OPENSCAD) -s test_hollow_cube_import.stl test_hollow_cube_import.scad

test_hollow_cube_import_projection.scad : test_hollow_cube_import.stl
	echo "projection_cut=true;" > test_hollow_cube_import_projection.scad
	echo "projection(cut=projection_cut)" >> test_hollow_cube_import_projection.scad
	echo "  import_stl("'"'"test_hollow_cube_import.stl"'"'");" >> test_hollow_cube_import_projection.scad

test_hollow_cube_import_projection_true.dxf : test_hollow_cube_import_projection.scad
	$(OPENSCAD) -D projection_cut=true -x test_hollow_cube_import_projection_true.dxf test_hollow_cube_import_projection.scad

test_hollow_cube_import_projection_false.dxf : test_hollow_cube_import_projection.scad
	$(OPENSCAD) -D projection_cut=false -x test_hollow_cube_import_projection_false.dxf test_hollow_cube_import_projection.scad

test_complex_cube_import.stl : test_complex_cube_import.scad
	$(OPENSCAD) -s test_complex_cube_import.stl test_complex_cube_import.scad

test_complex_cube_import_projection.scad : test_complex_cube_import.stl
	echo "projection_cut=true;" > test_complex_cube_import_projection.scad
	echo "projection(cut=projection_cut)" >> test_complex_cube_import_projection.scad
	echo "  import_stl("'"'"test_complex_cube_import.stl"'"'");" >> test_complex_cube_import_projection.scad

test_complex_cube_import_projection_true.dxf : test_complex_cube_import_projection.scad
	$(OPENSCAD) -D projection_cut=true -x test_complex_cube_import_projection_true.dxf test_complex_cube_import_projection.scad

test_complex_cube_import_projection_false.dxf : test_complex_cube_import_projection.scad
	$(OPENSCAD) -D projection_cut=false -x test_complex_cube_import_projection_false.dxf test_complex_cube_import_projection.scad

intersection_projection_true_diff.scad : test_complex_cube_projection_true.dxf test_complex_cube_import_projection_true.dxf
	echo "intersection() {" > intersection_projection_true_diff.scad
	echo "  import_dxf("'"'"test_complex_cube_projection_true.dxf"'"'");" >> intersection_projection_true_diff.scad
	echo "  import_dxf("'"'"test_complex_cube_import_projection_true.dxf"'"'");" >> intersection_projection_true_diff.scad
	echo "}" >> intersection_projection_true_diff.scad

intersection_projection_true_diff.dxf : intersection_projection_true_diff.scad
	$(OPENSCAD) -x intersection_projection_true_diff.dxf intersection_projection_true_diff.scad

clean :
	$(RM) *.stl
	$(RM) *.scad
	$(RM) *.dxf

